spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver
          schema: classpath:db/schema.sql
          data: classpath:db/data.sql
        slave_1:
          username: sa
          password: 1234
          url: jdbc:h2:mem:test1
          driver-class-name: org.h2.Driver
          schema: classpath:db/schema.sql
        slave_2:
          username: sa
          password: ""
          url: jdbc:h2:mem:test2
          driver-class-name: org.h2.Driver
        slave_3:
          username: sa
          password: ""
          url: jdbc:h2:mem:test3
          driver-class-name: org.h2.Driver
        slave_4:
          url: jdbc:mysql://47.111.115.226:3306/test?serverTimezone=GMT%2B8&amp&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: ffcs_rp
  h2:
    console:
      enabled: true
      path: /h2-console



logging:
  level:
    com.baomidou: debug
swagger:
  base-package: com.baomidou.samples.ds.controller
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
